apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boutique-services
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - boutique
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
      app.kubernetes.io/part-of: boutique
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
