apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boutique
  namespace: argocd
spec:
  project: default
  source:
    # TODO: Replace with your own fork's URL before applying
    repoURL: 'https://github.com/<YOUR_GITHUB_USERNAME>/devops-ai-playbook.git'
    targetRevision: main
    path: gitops
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: boutique
  syncPolicy: {}
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
